/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibraryManagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class adminpage extends javax.swing.JFrame {
    
    int userid;
    //ResultSet rs=null;
    /**
     * Creates new form adminpage
     */
    public adminpage() {
        initComponents();
        radioButtonGroup();
        labelname.setText(TemporaryData.getCurrentUser().getFullname());
        labeluserid.setText("User ID :"+TemporaryData.getCurrentUser().getUserid());   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panelcontol = new javax.swing.JPanel();
        btnadduser = new javax.swing.JButton();
        btnviewuser = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        labeluserid = new javax.swing.JLabel();
        labelname = new javax.swing.JLabel();
        panelcenter = new javax.swing.JPanel();
        paneladduser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tffullname = new javax.swing.JTextField();
        tfdob = new javax.swing.JTextField();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        rbothers = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfaddress = new javax.swing.JTextArea();
        tfphno = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        labelnotif = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rblibrarian = new javax.swing.JRadioButton();
        rbuser = new javax.swing.JRadioButton();
        panelviewusers = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblviewuser = new javax.swing.JTable();
        btnsearch = new javax.swing.JButton();
        tfsearchuser = new javax.swing.JTextField();
        btndeleteuser = new javax.swing.JButton();
        btnedituser = new javax.swing.JButton();
        paneledituser = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labelfullname = new javax.swing.JLabel();
        labeldob = new javax.swing.JLabel();
        labeladdress = new javax.swing.JLabel();
        labelgender = new javax.swing.JLabel();
        labelphno = new javax.swing.JLabel();
        labelemail = new javax.swing.JLabel();
        tffullname1 = new javax.swing.JTextField();
        tfdob1 = new javax.swing.JTextField();
        rbmale1 = new javax.swing.JRadioButton();
        rbfemale1 = new javax.swing.JRadioButton();
        rbothers1 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfaddress1 = new javax.swing.JTextArea();
        tfphno1 = new javax.swing.JTextField();
        tfemail1 = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        labelnotif1 = new javax.swing.JLabel();
        labeltype = new javax.swing.JLabel();
        rblibrarian1 = new javax.swing.JRadioButton();
        rbuser1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new java.awt.BorderLayout());

        panelcontol.setBackground(new java.awt.Color(196, 203, 205));

        btnadduser.setText("Add User");
        btnadduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadduserActionPerformed(evt);
            }
        });

        btnviewuser.setText("View Users");
        btnviewuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewuserActionPerformed(evt);
            }
        });

        btnlogout.setText("Log Out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelcontolLayout = new javax.swing.GroupLayout(panelcontol);
        panelcontol.setLayout(panelcontolLayout);
        panelcontolLayout.setHorizontalGroup(
            panelcontolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnviewuser, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
            .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
            .addComponent(btnadduser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelcontolLayout.createSequentialGroup()
                .addGroup(panelcontolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labeluserid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelcontolLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelcontolLayout.setVerticalGroup(
            panelcontolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontolLayout.createSequentialGroup()
                .addComponent(labelname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labeluserid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(btnadduser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnviewuser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jPanel3.add(panelcontol, java.awt.BorderLayout.LINE_START);

        panelcenter.setBackground(new java.awt.Color(254, 254, 254));
        panelcenter.setLayout(new java.awt.CardLayout());

        paneladduser.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 36)); // NOI18N
        jLabel1.setText("Create User");

        jLabel2.setText("Full Name");

        jLabel3.setText("Date of Birth");

        jLabel4.setText("Address");

        jLabel5.setText("Gender");

        jLabel6.setText("Phone No.");

        jLabel7.setText("Email");

        tffullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffullnameActionPerformed(evt);
            }
        });

        tfdob.setText("YYYY/MM/DD");
        tfdob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfdobFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdobFocusLost(evt);
            }
        });

        rbmale.setText("Male");

        rbfemale.setText("Female");

        rbothers.setText("Others");

        tfaddress.setColumns(20);
        tfaddress.setRows(5);
        jScrollPane1.setViewportView(tfaddress);

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        labelnotif.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel8.setText("Type");

        rblibrarian.setText("Librarian");

        rbuser.setText("User");

        javax.swing.GroupLayout paneladduserLayout = new javax.swing.GroupLayout(paneladduser);
        paneladduser.setLayout(paneladduserLayout);
        paneladduserLayout.setHorizontalGroup(
            paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneladduserLayout.createSequentialGroup()
                .addGap(0, 253, Short.MAX_VALUE)
                .addComponent(labelnotif, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(paneladduserLayout.createSequentialGroup()
                .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladduserLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneladduserLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(55, 55, 55)
                        .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfdob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfemail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneladduserLayout.createSequentialGroup()
                                    .addComponent(rbmale)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbfemale)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbothers))
                                .addComponent(tffullname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfphno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneladduserLayout.createSequentialGroup()
                                .addComponent(rblibrarian)
                                .addGap(18, 18, 18)
                                .addComponent(rbuser))))
                    .addGroup(paneladduserLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneladduserLayout.setVerticalGroup(
            paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladduserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tffullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbfemale)
                    .addComponent(rbothers)
                    .addComponent(rbmale))
                .addGap(19, 19, 19)
                .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneladduserLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneladduserLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(22, 22, 22)
                .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfphno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(22, 22, 22)
                .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rblibrarian)
                    .addComponent(rbuser))
                .addGap(18, 18, 18)
                .addGroup(paneladduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreset)
                    .addComponent(btnsubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(labelnotif, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelcenter.add(paneladduser, "card2");

        panelviewusers.setBackground(new java.awt.Color(254, 254, 254));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel9.setText("Users");

        tblviewuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblviewuser);

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        tfsearchuser.setText("Enter the User ID or Name");
        tfsearchuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfsearchuserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfsearchuserFocusLost(evt);
            }
        });
        tfsearchuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsearchuserActionPerformed(evt);
            }
        });

        btndeleteuser.setBackground(new java.awt.Color(246, 90, 90));
        btndeleteuser.setText("Delete");
        btndeleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteuserActionPerformed(evt);
            }
        });

        btnedituser.setText("Edit ");
        btnedituser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedituserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelviewusersLayout = new javax.swing.GroupLayout(panelviewusers);
        panelviewusers.setLayout(panelviewusersLayout);
        panelviewusersLayout.setHorizontalGroup(
            panelviewusersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewusersLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(panelviewusersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfsearchuser, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelviewusersLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnedituser, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndeleteuser)
                .addGap(40, 40, 40))
            .addGroup(panelviewusersLayout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelviewusersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelviewusersLayout.setVerticalGroup(
            panelviewusersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewusersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(57, 57, 57)
                .addGroup(panelviewusersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearch)
                    .addComponent(tfsearchuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndeleteuser)
                    .addComponent(btnedituser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        panelcenter.add(panelviewusers, "card3");

        paneledituser.setBackground(new java.awt.Color(254, 254, 254));

        jLabel10.setFont(new java.awt.Font("Courier 10 Pitch", 0, 36)); // NOI18N
        jLabel10.setText("Edit User");

        labelfullname.setText("Full Name");

        labeldob.setText("Date of Birth");

        labeladdress.setText("Address");

        labelgender.setText("Gender");

        labelphno.setText("Phone No.");

        labelemail.setText("Email");

        tffullname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffullname1ActionPerformed(evt);
            }
        });

        tfdob1.setText("YYYY/MM/DD");
        tfdob1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfdob1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdob1FocusLost(evt);
            }
        });

        rbmale1.setText("Male");

        rbfemale1.setText("Female");

        rbothers1.setText("Others");

        tfaddress1.setColumns(20);
        tfaddress1.setRows(5);
        jScrollPane3.setViewportView(tfaddress1);

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        labelnotif1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        labeltype.setText("Type");

        rblibrarian1.setText("Librarian");

        rbuser1.setText("User");

        javax.swing.GroupLayout paneledituserLayout = new javax.swing.GroupLayout(paneledituser);
        paneledituser.setLayout(paneledituserLayout);
        paneledituserLayout.setHorizontalGroup(
            paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneledituserLayout.createSequentialGroup()
                .addGap(0, 253, Short.MAX_VALUE)
                .addComponent(labelnotif1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(paneledituserLayout.createSequentialGroup()
                .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneledituserLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel10))
                    .addGroup(paneledituserLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneledituserLayout.createSequentialGroup()
                                .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelgender)
                                    .addComponent(labeldob)
                                    .addComponent(labelfullname)
                                    .addComponent(labelphno)
                                    .addComponent(labeladdress)
                                    .addComponent(labelemail)
                                    .addComponent(labeltype))
                                .addGap(55, 55, 55)
                                .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneledituserLayout.createSequentialGroup()
                                        .addComponent(rblibrarian1)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbuser1))
                                    .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfdob1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfemail1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneledituserLayout.createSequentialGroup()
                                            .addComponent(rbmale1)
                                            .addGap(18, 18, 18)
                                            .addComponent(rbfemale1)
                                            .addGap(18, 18, 18)
                                            .addComponent(rbothers1))
                                        .addComponent(tffullname1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfphno1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(paneledituserLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneledituserLayout.setVerticalGroup(
            paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneledituserLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addGap(52, 52, 52)
                .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelfullname)
                    .addComponent(tffullname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelgender)
                    .addComponent(rbfemale1)
                    .addComponent(rbothers1)
                    .addComponent(rbmale1))
                .addGap(19, 19, 19)
                .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeldob)
                    .addComponent(tfdob1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labeladdress)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfphno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelphno))
                .addGap(22, 22, 22)
                .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfemail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelemail))
                .addGap(26, 26, 26)
                .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeltype)
                    .addComponent(rblibrarian1)
                    .addComponent(rbuser1))
                .addGap(18, 18, 18)
                .addGroup(paneledituserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel)
                    .addComponent(btnupdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(labelnotif1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelcenter.add(paneledituser, "card2");

        jPanel3.add(panelcenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewuserActionPerformed
        displayViewUserPage();
    }//GEN-LAST:event_btnviewuserActionPerformed

    private void btnadduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadduserActionPerformed
        panelviewusers.setVisible(false);
        paneladduser.setVisible(true);
        paneledituser.setVisible(false);
    }//GEN-LAST:event_btnadduserActionPerformed

    private void tfsearchuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsearchuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsearchuserActionPerformed

    private void tfsearchuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfsearchuserFocusGained
        if(tfsearchuser.getText().equalsIgnoreCase("Enter the User ID or Name")){
            tfsearchuser.setText("");
        }
    }//GEN-LAST:event_tfsearchuserFocusGained

    private void tfsearchuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfsearchuserFocusLost
        if(tfsearchuser.getText().equalsIgnoreCase("")){
            tfsearchuser.setText("Enter the User ID or Name");
        }
    }//GEN-LAST:event_tfsearchuserFocusLost

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        dispose();
        TemporaryData.setCurrentUser(null);
        (new loginFrame()).setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void tffullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffullnameActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
       clear();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
       Connection con=Connect.connectDB();
        PreparedStatement pst;
        ResultSet rs=null;
        try{
            String sql="insert into usertable(password,fullname,gender,dob,address,phno,email,type) values(?,?,?,?,?,?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(2,tffullname.getText());
            pst.setString(1,tfdob.getText());
            if(rbmale.isSelected()){
                pst.setString(3,"male");
            }
            else if (rbfemale.isSelected()) {
                pst.setString(3,"female");
            }
            else{
                pst.setString(3,"others");
            }
            pst.setString(4,tfdob.getText());
            pst.setString(5,tfaddress.getText());
            pst.setString(6,tfphno.getText());
            pst.setString(7,tfemail.getText());
            if(rblibrarian.isSelected()){
                pst.setString(8,"librarian");
            }
            if(rbuser.isSelected()){
                pst.setString(8,"user");
            }
            int count = pst.executeUpdate();
            
          //  sql="select MAX(userid) from usertable";
            if(count==1){
                sql="select MAX(userid) as userid from usertable";
                pst=con.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    int userid=rs.getInt("userid");
                    JOptionPane.showMessageDialog(this,"successfully uploaded\nUser ID of "+tffullname.getText()+" : "+userid);
                    clear();
                    con.close();
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"faild");
                clear();
                con.close();
            }
            //System.out.println("total statements inserted = "+count);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,"sqlexception in btnsubmitActionPerformed\n"+e);
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void tfdobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdobFocusGained
        if(tfdob.getText().equalsIgnoreCase("YYYY/MM/DD")){
            tfdob.setText("");
        }
    }//GEN-LAST:event_tfdobFocusGained

    private void tfdobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdobFocusLost
        if(tfdob.getText().equalsIgnoreCase("")){
            tfdob.setText("YYYY/MM/DD");
        }
    }//GEN-LAST:event_tfdobFocusLost

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        Connection con=Connect.connectDB();
        PreparedStatement pst;
        ResultSet rs=null;
        destroyTable();
        DefaultTableModel mod =(DefaultTableModel) tblviewuser.getModel();
        con=Connect.connectDB();
        String sql="select * from usertable where userid=?";
        String[] columns = new String[] {
                "User ID", "Full Name", "Gender","Date of bith","address","Ph No.","Email","Type"
            };
        Object[][] tdata = new Object[1][9];
        try{
            //pst=con.prepareStatement(sql);
            pst=con.prepareStatement(sql);
            pst.setInt(1,Integer.valueOf(tfsearchuser.getText()));
            rs = pst.executeQuery();
            int i=0;
            if(rs.next()){
                tdata[i][0]=rs.getInt("userid");
                tdata[i][1]=rs.getString("fullname");
                tdata[i][2]=rs.getString("gender");
                tdata[i][3]=rs.getString("dob");
                tdata[i][4]=rs.getString("address");
                tdata[i][5]=rs.getString("phno");
                tdata[i][6]=rs.getString("email");
                tdata[i][7]=rs.getString("type");
            }
            mod.setDataVector(tdata, columns);
            con.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btndeleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteuserActionPerformed
                   DefaultTableModel mod =(DefaultTableModel) tblviewuser.getModel();
        Connection con=Connect.connectDB();
        PreparedStatement pst;
        ResultSet rs=null;
            if(tblviewuser.getSelectedRow()!= -1){
                int i=tblviewuser.getSelectedRow();
                int c=0;
                int userid = (int) tblviewuser.getModel().getValueAt(i,c);
                
                //JOptionPane.showMessageDialog(this, "valuse of  rowselected value  "+value);
                int Conf=JOptionPane.showConfirmDialog(this,"Are yousure to delete?","Confirm",JOptionPane.YES_NO_OPTION);
                if(Conf==JOptionPane.YES_OPTION){
                   con=Connect.connectDB();
                    String sql="delete from usertable where userid=?";
                    try {
                        pst=con.prepareStatement(sql);
                        pst.setInt(1,userid);
                        pst.execute();
                        con.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(adminpage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                   mod.removeRow(tblviewuser.getSelectedRow()) ;
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "plz select the user row");
            }
        
        
    }//GEN-LAST:event_btndeleteuserActionPerformed

    private void tffullname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffullname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffullname1ActionPerformed

    private void tfdob1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdob1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdob1FocusGained

    private void tfdob1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdob1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdob1FocusLost

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        Connection con=Connect.connectDB();
        PreparedStatement pst;
        ResultSet rs=null;
        String sql="update usertable set fullname=?,gender=?,dob=?,address=?,phno=?,email=?,type=? where userid=?";
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,tffullname1.getText());
            if(rbmale1.isSelected()){
                pst.setString(2,"male");
            }
            else if (rbfemale1.isSelected()) {
                pst.setString(2,"female");
            }
            else{
                pst.setString(2,"others");
            }
            pst.setString(3,tfdob1.getText());
            pst.setString(4,tfaddress1.getText());
            pst.setString(5,tfphno1.getText());
            pst.setString(6,tfemail1.getText());
            if(rblibrarian.isSelected()){
                pst.setString(7,"librarian");
            }
            if(rbuser1.isSelected()){
                pst.setString(7,"user");
            }
            pst.setInt(8,userid);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Updated\n");
            clear();
        }
        catch(SQLException e){
                JOptionPane.showMessageDialog(this,e);
        }
        paneledituser.setVisible(false);
        displayViewUserPage();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        paneledituser.setVisible(false);
        panelviewusers.setVisible(true);
        tableData();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnedituserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedituserActionPerformed
        Connection con=Connect.connectDB();
        PreparedStatement pst;
        ResultSet rs=null;
        if(tblviewuser.getSelectedRow()!= -1){
                int i=tblviewuser.getSelectedRow();
                int c=0;
                userid=(int) tblviewuser.getModel().getValueAt(i,c);
                
                //JOptionPane.showMessageDialog(this, "valuse of  rowselected value  "+value);
                
                    String sql="select * from usertable where userid=?";
                    try {
                        pst=con.prepareStatement(sql);
                        pst.setInt(1,userid);
                        rs=pst.executeQuery();
                        if(rs.next()){
                            tffullname1.setText(rs.getString("fullname"));
                            if(rs.getString("gender").equals("male")){
                                rbmale1.setSelected(true);
                            }
                            else if(rs.getString("gender").equals("female")){
                                rbfemale1.setSelected(true);
                            }
                            else{
                                rbothers1.setSelected(true);
                            }
                            tfdob1.setText(rs.getString("dob"));
                            tfaddress1.setText(rs.getString("address"));
                            tfphno1.setText(rs.getString("phno"));
                            tfemail1.setText(rs.getString("email"));
                            if(rs.getString("type").equals("librarian")){
                                rblibrarian1.setSelected(true);
                            }
                            else
                            {
                                rbuser1.setSelected(true);
                            }
                        }
                        con.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(adminpage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                panelviewusers.setVisible(false);
                paneladduser.setVisible(false);
                paneledituser.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "plz select the user row");
            }
        
    }//GEN-LAST:event_btnedituserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadduser;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndeleteuser;
    private javax.swing.JButton btnedituser;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnviewuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labeladdress;
    private javax.swing.JLabel labeldob;
    private javax.swing.JLabel labelemail;
    private javax.swing.JLabel labelfullname;
    private javax.swing.JLabel labelgender;
    private javax.swing.JLabel labelname;
    private javax.swing.JLabel labelnotif;
    private javax.swing.JLabel labelnotif1;
    private javax.swing.JLabel labelphno;
    private javax.swing.JLabel labeltype;
    private javax.swing.JLabel labeluserid;
    private javax.swing.JPanel paneladduser;
    private javax.swing.JPanel panelcenter;
    private javax.swing.JPanel panelcontol;
    private javax.swing.JPanel paneledituser;
    private javax.swing.JPanel panelviewusers;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbfemale1;
    private javax.swing.JRadioButton rblibrarian;
    private javax.swing.JRadioButton rblibrarian1;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JRadioButton rbmale1;
    private javax.swing.JRadioButton rbothers;
    private javax.swing.JRadioButton rbothers1;
    private javax.swing.JRadioButton rbuser;
    private javax.swing.JRadioButton rbuser1;
    private javax.swing.JTable tblviewuser;
    private javax.swing.JTextArea tfaddress;
    private javax.swing.JTextArea tfaddress1;
    private javax.swing.JTextField tfdob;
    private javax.swing.JTextField tfdob1;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfemail1;
    private javax.swing.JTextField tffullname;
    private javax.swing.JTextField tffullname1;
    private javax.swing.JTextField tfphno;
    private javax.swing.JTextField tfphno1;
    private javax.swing.JTextField tfsearchuser;
    // End of variables declaration//GEN-END:variables

    private void radioButtonGroup() {
        ButtonGroup bgrbgender =new ButtonGroup();
        ButtonGroup bgrbtype = new ButtonGroup();
        
       bgrbgender.add(rbmale);
       bgrbgender.add(rbfemale);
       bgrbgender.add(rbothers);
       bgrbtype.add(rblibrarian);
       bgrbtype.add(rbuser);
    }

    private void clear() {
       tffullname.setText("");
       tfdob.setText("YYYY/MM/DD");
       tfaddress.setText("");
       tfphno.setText("");
       tfemail.setText("");
       rbfemale.setSelected(false);
       rblibrarian.setSelected(false);
       rbmale.setSelected(false);
       rbothers.setSelected(false);
       rbuser.setSelected(false);
       tffullname1.setText("");
       tfdob1.setText("YYYY/MM/DD");
       tfaddress1.setText("");
       tfphno1.setText("");
       tfemail1.setText("");
       rbfemale1.setSelected(false);
       rblibrarian1.setSelected(false);
       rbmale1.setSelected(false);
       rbothers1.setSelected(false);
       rbuser1.setSelected(false);
       
    }

    private void tableData() {
        

        try{
            ResultSet rs;
            DefaultTableModel mod =(DefaultTableModel) tblviewuser.getModel();
            int rowsCount=getTableRowCount("select count(*) as rowscount from usertable");
            String[] columns = new String[] {
                "User ID", "Full Name", "Gender","Date of bith","address","Ph No.","Email","Type"
            };
            Object[][] tdata = new Object[rowsCount][9];
            int i=0;
            rs=getTableData();
            rs.next();
            while(rs.next()){
                tdata[i][0]=rs.getInt("userid");
                tdata[i][1]=rs.getString("fullname");
                tdata[i][2]=rs.getString("gender");
                tdata[i][3]=rs.getString("dob");
                tdata[i][4]=rs.getString("address");
                tdata[i][5]=rs.getString("phno");
                tdata[i][6]=rs.getString("email");
                tdata[i][7]=rs.getString("type");
                i++;
            }
            mod.setDataVector(tdata, columns);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,"sqlexception in tableData\n"+e);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this,"exception in tableData\n"+e);
        }
        
    }
    private ResultSet getTableData() {
        Connection con;
        con=Connect.connectDB();
        ResultSet rs=null;
        PreparedStatement pst;
        String sql="select * from usertable";
        try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            //con.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "sqlexception in getTableData\n"+e);
        }
        return rs;
    }

    private int getTableRowCount(String sql){
        int i=0;
        Connection con;
        con=Connect.connectDB();
        ResultSet rs=null;
        PreparedStatement pst;
        try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                i=rs.getInt("rowscount");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "sqlexception in getTableRowCount\n"+e);
        }
        return i;  
    }
    private void destroyTable() {
        DefaultTableModel mod =(DefaultTableModel) tblviewuser.getModel();
        mod.getDataVector().removeAllElements();
        mod.fireTableDataChanged();
    }
    private void displayViewUserPage() {
        tableData();
        panelviewusers.setVisible(true);
        paneladduser.setVisible(false);
        paneledituser.setVisible(false);
    }
}