/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibraryManagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class loginFrame extends javax.swing.JFrame {
        
    /**
     * Creates new form loginFrame
     */
    public loginFrame() {
        initComponents();
        this.getRootPane().setDefaultButton(btnlogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfuserid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pfpwd = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(null);

        tfuserid.setBackground(new java.awt.Color(254, 254, 254));
        tfuserid.setBorder(null);
        tfuserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuseridActionPerformed(evt);
            }
        });
        jPanel1.add(tfuserid);
        tfuserid.setBounds(650, 250, 350, 30);

        jLabel1.setText("User ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(650, 230, 80, 16);

        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(650, 300, 80, 20);

        pfpwd.setBackground(new java.awt.Color(254, 254, 254));
        pfpwd.setBorder(null);
        jPanel1.add(pfpwd);
        pfpwd.setBounds(650, 320, 350, 30);

        btnlogin.setBackground(new java.awt.Color(1, 80, 160));
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(650, 380, 350, 30);

        jSeparator1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(640, 280, 370, 10);

        jSeparator2.setForeground(new java.awt.Color(1, 1, 1));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(640, 350, 370, 12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfuseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuseridActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        try{
            Connection con=Connect.connectDB();
            PreparedStatement pst;
            ResultSet rs=null;
            String sql="select * from usertable where userid=? and password=?";
            pst=con.prepareStatement(sql);
            pst.setInt(1,Integer.valueOf(tfuserid.getText()));
            pst.setString(2,String.valueOf(pfpwd.getPassword()));
            rs=pst.executeQuery();
            if(rs.next()){
                String type=rs.getString("type");
                String fullname=rs.getString("fullname");
                if(type.equals("admin")){
                    User userObj = new User(Integer.valueOf(tfuserid.getText()),fullname,type); 
                    TemporaryData.setCurrentUser(userObj);
                    userObj = TemporaryData.getCurrentUser();
                    dispose();
                    (new adminpage()).setVisible(true);
                }
                else if(type.equals("librarian")){
                    User userObj = new User(Integer.valueOf(tfuserid.getText()),fullname,type); 
                    TemporaryData.setCurrentUser(userObj);
                    userObj = TemporaryData.getCurrentUser();
                    dispose();
                    (new Librarianpage()).setVisible(true);
                }
                else{
                    User userObj = new User(Integer.valueOf(tfuserid.getText()),fullname,type); 
                    TemporaryData.setCurrentUser(userObj);
                    userObj = TemporaryData.getCurrentUser();
                    dispose();
                    (new Userpage()).setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"invalid userid or password");
            }
            con.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"invalid username");
        }
        
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame mainFrame = new loginFrame();
                mainFrame.setVisible(true);
                mainFrame.setTitle("Library Management");
                mainFrame.setName("Library Management");
                
            }
        });
    }
    
    private JButton getLoginButton() {
        return btnlogin;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pfpwd;
    private javax.swing.JTextField tfuserid;
    // End of variables declaration//GEN-END:variables
}
